### ISSUE TITLE
Error with server.js

### ISSUE THREAD

**Issue by hunterpl** [huytd/agar.io-clone#210]
Hello!

I have some errors from new version, of course I installed from fresh package, can you fix it?

/var/www/agar/server/server.js: line 205, col 13, 'console' is not defined. (W117)
/var/www/agar/server/server.js: line 228, col 24, 'console' is not defined. (W117)
/var/www/agar/server/server.js: line 231, col 24, 'console' is not defined. (W117)
/var/www/agar/server/server.js: line 244, col 13, 'console' is not defined. (W117)
/var/www/agar/server/server.js: line 295, col 21, 'console' is not defined. (W117)
/var/www/agar/server/server.js: line 296, col 21, 'console' is not defined. (W117)
/var/www/agar/server/server.js: line 297, col 21, 'console' is not defined. (W117)
/var/www/agar/server/server.js: line 322, col 17, 'process' is not defined. (W117)
/var/www/agar/server/server.js: line 322, col 52, 'process' is not defined. (W117)
/var/www/agar/server/server.js: line 323, col 18, 'process' is not defined. (W117)
/var/www/agar/server/server.js: line 323, col 55, 'process' is not defined. (W117)
/var/www/agar/server/server.js: line 324, col 5, 'process' is not defined. (W117)
/var/www/agar/server/server.js: line 326, col 9, 'console' is not defined. (W117)
/var/www/agar/server/server.js: line 330, col 9, 'console' is not defined. (W117)

**Comment by JuhQ** [comment]
This was fixed on my pr, pull again and it should be fine.

**Comment by hunterpl** [comment]
@JuhQ Still have the same issue.

**Comment by JuhQ** [comment]
I just pulled the master, runs through without problems.

```
➜  agar.io-clone git:(master) gulp run
[22:33:40] Using gulpfile ~/Sites/misc/agar.io-clone/gulpfile.js
[22:33:40] Starting 'lint-client'...
[22:33:40] Starting 'move-client'...
[22:33:40] Starting 'lint-server'...
[22:33:40] Starting 'move-server'...
[22:33:40] Finished 'lint-server' after 249 ms
[22:33:41] Finished 'lint-client' after 553 ms
[22:33:41] Finished 'move-server' after 521 ms
[22:33:41] Starting 'build-server'...
[22:33:41] Finished 'build-server' after 7.92 ms
[22:33:41] Finished 'move-client' after 575 ms
[22:33:41] Starting 'build-client'...
[22:33:41] Finished 'build-client' after 505 ms
[22:33:41] Starting 'build'...
[22:33:41] Finished 'build' after 13 μs
[22:33:41] Starting 'run'...
[22:33:41] Finished 'run' after 1.98 ms
[22:33:41] [nodemon] v1.3.7
[22:33:41] [nodemon] to restart at any time, enter `rs`
[22:33:41] [nodemon] watching: *.*
[22:33:41] [nodemon] starting `node server/server.js /server/config.json`
listening on *:3000
A user connected!
```

**Comment by hunterpl** [comment]
I just use command npm start for starting instance of server but still have the same issue.

**Comment by JuhQ** [comment]
Still no problems. Did you pull?

```
➜  agar.io-clone git:(master) npm start

> agar-clone@1.0.0 start /Users/juhatauriainen/Sites/misc/agar.io-clone
> node ./node_modules/gulp/bin/gulp.js run

[22:46:58] Using gulpfile ~/Sites/misc/agar.io-clone/gulpfile.js
[22:46:58] Starting 'lint-client'...
[22:46:58] Starting 'move-client'...
[22:46:58] Starting 'lint-server'...
[22:46:58] Starting 'move-server'...
[22:46:59] Finished 'lint-server' after 232 ms
[22:46:59] Finished 'lint-client' after 490 ms
[22:46:59] Finished 'move-server' after 473 ms
[22:46:59] Starting 'build-server'...
[22:46:59] Finished 'build-server' after 5.54 ms
[22:46:59] Finished 'move-client' after 527 ms
[22:46:59] Starting 'build-client'...
[22:47:00] Finished 'build-client' after 589 ms
[22:47:00] Starting 'build'...
[22:47:00] Finished 'build' after 9.45 μs
[22:47:00] Starting 'run'...
[22:47:00] Finished 'run' after 2.96 ms
[22:47:00] [nodemon] v1.3.7
[22:47:00] [nodemon] to restart at any time, enter `rs`
[22:47:00] [nodemon] watching: *.*
[22:47:00] [nodemon] starting `node server/server.js /server/config.json`
listening on *:3000
A user connected!
```

**Comment by hunterpl** [comment]
@JuhQ i just download as a ZIP file extract install and start it nothing more i didn't used a SVN for pull update.

**Comment by JoeMattie** [comment]
Um we are using git not svn. Also you need to run npm install to fetch
dependencies before running
